name: dart_ast_node_viewer
description: "A simple Dart AST node viewer."
publish_to: "none"
version: 0.3.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"
  flutter: ">=3.38.5"

dependencies:
  analyzer: ^8.4.0
  collection: ^1.19.1
  # Temporary fix for https://github.com/flutter/flutter/issues/119074
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  flutter_fancy_tree_view: ^1.6.0
  flutter_riverpod: ^3.1.0
  lucide_icons_flutter: ^3.1.10
  meta: ^1.16.0
  package_info_plus: ^9.0.0
  pub_semver: ^2.2.0
  re_editor: ^0.8.0
  re_highlight: ^0.0.3
  riverpod_annotation: ^4.0.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.11.1
  choco_lints:
    git:
      ref: v1.7.0
      url: https://github.com/charlescyt/choco_lints.git
  custom_lint: ^0.8.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Lato/
    - assets/fonts/JetBrainsMono/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700

    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Regular.ttf
